# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: Default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    codeCoverageToolOption: 'cobertura'
    #codeCoverageClassFilter: # Optional. Comma-separated list of filters to include or exclude classes from collecting code coverage. For example: +:com.*,+:org.*,-:my.app*.*
    #codeCoverageClassFilesDirectories: # Optional
    #codeCoverageSourceDirectories: # Optional
    #codeCoverageFailIfEmpty: false # Optional
  env:
    JAVA_HOME_8_X64: $(System.JavaHome)


- script: | 
   echo Write your commands here
   echo Hello world
   echo  $(System.DefaultWorkingDirectory)
   dotnet --version
   dotnet $(System.DefaultWorkingDirectory)/CoveragePublisher/CoveragePublisher.Console.dll  $(System.DefaultWorkingDirectory)\target\site\cobertura\coverage.xml
  displayName: 'Command Line Script'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
